/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as PokemonPokemonNameRouteImport } from './routes/pokemon/$pokemonName'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const PokemonPokemonNameRoute = PokemonPokemonNameRouteImport.update({
  id: '/pokemon/$pokemonName',
  path: '/pokemon/$pokemonName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/discover': typeof DiscoverRoute
  '/pokemon/$pokemonName': typeof PokemonPokemonNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/discover': typeof DiscoverRoute
  '/pokemon/$pokemonName': typeof PokemonPokemonNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/discover': typeof DiscoverRoute
  '/pokemon/$pokemonName': typeof PokemonPokemonNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/collection' | '/discover' | '/pokemon/$pokemonName'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/collection' | '/discover' | '/pokemon/$pokemonName'
  id: '__root__' | '/' | '/collection' | '/discover' | '/pokemon/$pokemonName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionRoute: typeof CollectionRoute
  DiscoverRoute: typeof DiscoverRoute
  PokemonPokemonNameRoute: typeof PokemonPokemonNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokemon/$pokemonName': {
      id: '/pokemon/$pokemonName'
      path: '/pokemon/$pokemonName'
      fullPath: '/pokemon/$pokemonName'
      preLoaderRoute: typeof PokemonPokemonNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionRoute: CollectionRoute,
  DiscoverRoute: DiscoverRoute,
  PokemonPokemonNameRoute: PokemonPokemonNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
